name: Tests

on:
  push:
    branches: [ "main" , "tmp" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: install dep
        run: sudo apt install -y libxi-dev libx11-dev libxss-dev libxtst-dev
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
